ssh_user = "ubuntu"

ireland_host = "54.77.232.166"
ireland_key = "C:\\Users\\Shini\\Documents\\PolyEdge.pem"

tokyo_host = "57.180.89.145"
tokyo_key = "C:\\Users\\Shini\\Documents\\dongjing.pem"

forge_service_ireland = "polyedge-forge-ireland.service"
forge_proxy_service_ireland = "polyedge-9180-proxy.service"
data_service_tokyo = "polyedge-forge-tokyo.service"
data_health_timer_ireland = "polyedge-forge-healthcheck.timer"
api_bind_port_ireland = 9810
